# Site settings
title: 娱乐360
email: kehao.wu@gmail.com
description: 传达最新娱乐资讯
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fun360.xyz" # the base hostname & protocol for your site
permalink: none
# Build settings
markdown: kramdown
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"